In [ ]:
# 1) Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a
#Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
# [
#  [5, 5, 5],
#  [5, 5, 5],
#  [5, 5, 5]
# ]


In [9]:
import numpy as np
def compute(a,b,c):# creating the computation function 
    d = np.full((a,b),c)
    return d
compute(3,3,5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [4]:
# or another inbuilt function
import numpy as np
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# or
import numpy as np
np.zeros([3,3],dtype=int) # to remove float

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
# or
import numpy as np
np.full((2,3),'d')

array([['d', 'd', 'd'],
       ['d', 'd', 'd']], dtype='<U1')

In [ ]:
# 2)  Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.

In [18]:
import numpy as np
a = np.array([[0,1,2],[1,2,3],[2,3,4],[3,4,0]])
b = np.array([[0,1,0]])
def array_addition(a,b):
    c=np.add(a,b)
    return c
array_addition(a,b)

array([[0, 2, 2],
       [1, 3, 3],
       [2, 4, 4],
       [3, 5, 0]])

In [ ]:
# 3) Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
#numbers N and M. The method should return the top-left N X M sub matrix e.g:
#  [
#   [1, 2, 3],
#   [4, 5, 6],
#   [7, 8, 9],
# ]

# top_left_sub_matrix (matrix, 2, 2) -> should return:
#  [
#   [1, 2]
#   [4, 5]
# ]

In [19]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
x[:2,:2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5]])

In [44]:
# or trainer method
import numpy as np
matrix = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3) # using reshape function 
matrix
def top_left(matrix,a,b):
    print(matrix[:a,:b])
top_left(matrix,2,2)    

[[1 2]
 [4 5]]


In [ ]:
# 4) Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
#numbers N and M The method should return the bottom-right N X M sub matrix e.g.: 
#  [
#   [1, 2, 3],
#   [4, 5, 6],
#   [7, 8, 9],
# ]
#sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 [
 [5, 6]
 [8, 9]
 ]


In [31]:
import numpy as np
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
y[1:,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

In [48]:
# or trainer method 
import numpy as np
matrix = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
matrix
def bottom_right(matrix,a,b):
    print(matrix[a:,b:])
bottom_right(matrix,1,1)

[[5 6]
 [8 9]]


In [ ]:
# 5) Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method should return a dictionary with
#'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:
# [1, 1, 1]
#solution(arr) -> should return :
 #{'mean': 1.0, 'std_dev': 0.0}


In [36]:
import numpy as np
arr = np.array([1,1,1])
print("Mean :", np.mean(arr), "std_dev :", np.std(arr))

Mean : 1.0 std_dev : 0.0


In [57]:
# or trainer method 
import numpy as np
a = np.array([1,1,1])
a
def stats(a):
    m = np.mean(a)
    n = np.std(a)
    o = np.median(a)
    dict = {'Mean': m, 'std_dev': n, 'Median': o}
    return dict
stats(a)

{'Mean': 1.0, 'std_dev': 0.0, 'Median': 1.0}