In [ ]:
# 1) Using sklearn import the wine dataset
# 2) Split the data into train and test 
# 3) Train the model
# 4) Make Predictions
# 5) Check accuracy using accuracy_score function


In [1]:
import pandas as pd
from sklearn.datasets import load_wine
data = load_wine()

In [5]:
y = data.target
y = pd.DataFrame(y)

In [6]:
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
173  2
174  2
175  2
176  2
177  2

[178 rows x 1 columns]

In [7]:
data

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [8]:
data.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [9]:
dt1 = data.data.tolist()
len(dt1)

178

In [10]:
dt1

[[14.23,
  1.71,
  2.43,
  15.6,
  127.0,
  2.8,
  3.06,
  0.28,
  2.29,
  5.64,
  1.04,
  3.92,
  1065.0],
 [13.2,
  1.78,
  2.14,
  11.2,
  100.0,
  2.65,
  2.76,
  0.26,
  1.28,
  4.38,
  1.05,
  3.4,
  1050.0],
 [13.16,
  2.36,
  2.67,
  18.6,
  101.0,
  2.8,
  3.24,
  0.3,
  2.81,
  5.68,
  1.03,
  3.17,
  1185.0],
 [14.37,
  1.95,
  2.5,
  16.8,
  113.0,
  3.85,
  3.49,
  0.24,
  2.18,
  7.8,
  0.86,
  3.45,
  1480.0],
 [13.24,
  2.59,
  2.87,
  21.0,
  118.0,
  2.8,
  2.69,
  0.39,
  1.82,
  4.32,
  1.04,
  2.93,
  735.0],
 [14.2,
  1.76,
  2.45,
  15.2,
  112.0,
  3.27,
  3.39,
  0.34,
  1.97,
  6.75,
  1.05,
  2.85,
  1450.0],
 [14.39,
  1.87,
  2.45,
  14.6,
  96.0,
  2.5,
  2.52,
  0.3,
  1.98,
  5.25,
  1.02,
  3.58,
  1290.0],
 [14.06,
  2.15,
  2.61,
  17.6,
  121.0,
  2.6,
  2.51,
  0.31,
  1.25,
  5.05,
  1.06,
  3.58,
  1295.0],
 [14.83,
  1.64,
  2.17,
  14.0,
  97.0,
  2.8,
  2.98,
  0.29,
  1.98,
  5.2,
  1.08,
  2.85,
  1045.0],
 [13.86,
  1.35,
  2.27,
  16.0,
  9

In [12]:
dt2 = data.feature_names
dt2

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [16]:
dta = pd.DataFrame()
dta = pd.DataFrame(dt1,columns = dt2)
x = dta
x.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [17]:
y.head()

0
0  0
1  0
2  0
3  0
4  0

In [21]:
# Splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)  #assuming 30% of data in testing set

In [22]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((124, 13), (54, 13), (124, 1), (54, 1))

In [ ]:
# model are applied for above splitted data - Training the model
# Decision tree classifier

In [24]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dt = dtc.fit(x_train,y_train)


In [26]:
# predicting
y_pred_dtc = dt.predict(x_test)
y_pred_dtc

array([0, 1, 0, 2, 0, 2, 1, 1, 1, 1, 1, 2, 0, 2, 1, 2, 0, 2, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 2, 1, 0, 1, 0, 0, 2, 1, 0, 0, 1, 2, 1, 2, 0,
       2, 2, 2, 0, 1, 0, 1, 0, 2, 1])

In [27]:
from sklearn.metrics import accuracy_score

In [ ]:
# Random forest 

In [30]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rf = rfc.fit(x_train,y_train)

<ipython-input-30-2c789f13b6b5>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf = rfc.fit(x_train,y_train)


In [33]:
y_pred_rfc=rf.predict(x_test)
y_pred_rfc

array([0, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 1, 2, 1, 2, 0,
       2, 2, 2, 0, 1, 0, 0, 0, 2, 1])

In [38]:
# Linear Regression
from sklearn import linear_model
lr = linear_model.LinearRegression()


In [39]:
lrc = lr.fit(x_train,y_train)
lrc

LinearRegression()

In [40]:
lr1 = lrc.predict(x_test)

In [42]:
import numpy as np
lr1 = np.hstack(lr1)
lr1 = lr1.astype(int)
lr1

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 0,
       1, 2, 1, 0, 1, 0, 0, 0, 2, 0])

In [43]:
y_test.head()

0
50   0
75   1
66   1
135  2
46   0

In [44]:
print('Accuracy score of Decision tree classifier',accuracy_score(y_test,y_pred_dtc))

Accuracy score of Decision tree classifier 0.8518518518518519


In [45]:
print('Accuracy score of Random Forest classifier',accuracy_score(y_test,y_pred_rfc))

Accuracy score of Random Forest classifier 0.9629629629629629


In [46]:
print('Accuracy score of Linear Regression',accuracy_score(y_test,lr1))

Accuracy score of Linear Regression 0.5


In [ ]:
#when we apply the Random forest it gives accurate result than that of other models 