<h1>
    <b>
        NUMPY</b>
    </h>


NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

<b>What is NumPy?</b>

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

It is an open source project and you can use it freely.

<b>Why Use NumPy?</b>

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

<b>Why is NumPy Faster Than Lists?</b>

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

<b>NumPy Getting Started</b>

Installation of NumPy

If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command:

<b>pip install numpy</b>

Import NumPy
Once NumPy is installed, import it in your applications by adding the import keyword:

In [4]:
pip install numpy # run this only if you are getting no module found error


In [5]:
import numpy

Now NumPy is imported and ready to use.

Example:

In [6]:
arr = numpy.array([1,2,3,4])
arr

array([1, 2, 3, 4])

<b>NumPy as np</b>

NumPy is usually imported under the np alias.

<b>alias:</b> In Python alias are an alternate name for referring to the same thing.

Create an alias with the as keyword while importing:

In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

Now the NumPy package can be referred to as np instead of numpy.

In [8]:
np.__version__

'1.19.2'

<b>NumPy Creating Arrays</b>

Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [9]:
arr = np.array([10,20,30])
print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

Example

Use a tuple to create a NumPy array:

In [11]:
arr = np.array((1,2,3))
print(arr)
type(arr)


[1 2 3]


numpy.ndarray

<b>Dimensions in Arrays</b>

A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

<b>0-D Arrays</b>

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

Example

Create a 0-D array with value 42

In [13]:
arr=np.array(42)
arr

array(42)

<b>1-D Arrays</b>

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

Example
Create a 1-D array containing the values 1,2,3,4,5:

In [14]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

<b>2-D Arrays</b>

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

Example
Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

<b>3-D arrays</b>

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.


In [17]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
[1,2,3]-----1D
[[1,2,3],[4,5,6]] ----2D
[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]] -----3D

SyntaxError: invalid syntax (<ipython-input-18-016229af4680>, line 1)

In [21]:
three_dim_list = [
                   [[111,112,113],
                    [121,122,123],
                    [131,132,133]],
    
                   [[211,212,213],
                    [221,222,223],
                    [231,232,233]],
    
                   [[311,312,313],
                    [321,322,323],
                    [331,332,333]]
    
               ]
len(three_dim_list)

3

In [24]:
for i in range(3):
    for j in range(3):
        for k in range(3):
            print(three_dim_list[i][j][k], end=' ')
        print()
    print()

111 112 113 
121 122 123 
131 132 133 

211 212 213 
221 222 223 
231 232 233 

311 312 313 
321 322 323 
331 332 333 



<b>Check Number of Dimensions?</b>

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

Example
Check how many dimensions the arrays have:

In [25]:
a = np.array(42)
b =np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


<b>Higher Dimensional Arrays</b>

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

Example
Create an array with 5 dimensions and verify that it has 5 dimensions:

In [81]:
a = np.array(range(20),ndmin = 6)
print(a)
print(a.ndim)


[[[[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]]]]]
6


<h2>NumPy Array Indexing</h2>

<b>Access Array Elements</b>

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

Example

Get the first element from the following array:

In [31]:
arr = np.array([1,2,3,4])
print(arr[1])

2


Example

Get third and fourth elements from the following array and add them.

In [32]:
arr = np.array([1,2,3,4])
print(arr[1] + arr[2])

5


<b>Access 2-D Arrays</b>

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Example

Access the 2nd element on 1st dim:

In [35]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("second element on 1dim is:",arr[0,3])

second element on 1dim is: 4


<b>Access 3-D Arrays</b>

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

Example
Access the third element of the second array of the first array:

In [39]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0][1][2])

6


<b>Negative Indexing</b>

Use negative indexing to access an array from the end.

Example

Print the last element from the 2nd dim:

In [44]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[-2,-5])

1


<h1>NumPy Array Slicing</h1>

<b>Slicing arrays</b>

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Example
Slice elements from index 1 to index 5 from the following array:

In [69]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[0:4])

[1 2 3 4]


Example

Slice elements from index 4 to the end of the array:

In [73]:
arr[5:]

array([6, 7])

<b>Negative Slicing</b>

Use the minus operator to refer to an index from the end:

Example

Slice from the index 3 from the end to index 1 from the end:

In [53]:
arr = np.array([1,2,3,4,5,6,7])
arr[-7:-3]

array([1, 2, 3, 4])

<b>STEP</b>

Use the step value to determine the step of the slicing:

Example

Return every other element from index 1 to index 5:

In [55]:
arr = np.array([1,2,3,4,5,6,7,8])
arr[1:8:2]

array([2, 3, 4, 5, 6, 7, 8])

Example

Return every other element from the entire array:

In [56]:
arr[::2]

array([1, 3, 5, 7])

Slicing 2-D Arrays

Example

From the second element, slice elements from index 1 to index 4 (not included):

In [75]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[-1,-5:-2])

[6 7 8]


Example

From both elements, return index 2:

In [62]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,3])

[4 9]


Example

From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [66]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:,1:4])

[[2 3 4]
 [7 8 9]]


<h2>NumPy Data Types</h2>

Data Types in Python

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j
    
Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

Checking the Data Type of an Array

The NumPy array object has a property called dtype that returns the data type of the array:

Example
    
Get the data type of an array object:

In [67]:
arr = np.array([1,2,3])
print(arr.dtype)
type(arr)

int32


numpy.ndarray

<b>NumPy Array Copy vs View</b>

The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

<b>COPY:</b>
    
Example

Make a copy, change the original array, and display both arrays:

In [76]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 50
print(arr)
print(x)

[50  2  3  4  5]
[1 2 3 4 5]


<b>VIEW:</b>
    
Example

Make a view, change the original array, and display both arrays:

The view SHOULD be affected by the changes made to the original array.

In [77]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] =42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Make Changes in the VIEW:

Example

Make a view, change the view, and display both arrays:

In [78]:
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] =21
print(arr)
print(x)

[21  2  3  4  5]
[21  2  3  4  5]


In [79]:
arr = np.array([[[1,2,3,4]]],ndmin=2)
print(arr)
print("dimensions", arr.ndim)


[[[1 2 3 4]]]
dimensions 3
