In [ ]:
# 1) Create a 3x3 matrix array with values ranging from 2 to 10

In [13]:
#Simple way
import numpy as np
arr1 = np.array([2,3,4,5,6,7,8,9,10]).reshape(3,3)
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [11]:
# or using arange function
import numpy as np
arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
# 2) Create a numpy array having user input values and convert the integer type to the float type of the elements of the array.
# For instance:
#     Original array :  [1, 2, 3, 4]
#    Array converted to a float type:  [1. 2. 3. 4.]

In [28]:
# using user input list
import numpy as np
Original_array = list(map(int,input().split()))
float_array = np.asarray(Original_array)

1 2 3 4


In [33]:
float_array = float_array.astype('float64') # or can use float_array = np.array(float_array,dtype='float64')
print(float_array)

[1. 2. 3. 4.]


In [23]:
# or without using user input list
import numpy as np
Original_array = np.array([1,2,3,4])
float_array = Original_array.astype(float)
print(float_array)

[1. 2. 3. 4.]


In [ ]:
# 3) Write a Numpy program to append values to the end of an array. For instance:
# Original array: [10, 20, 30]
# After append values to the end of the array:  [10 20 30 40 50 60 70 80 90]

In [14]:
import numpy as np
Original_Array = np.array([10,20,30])
Appended_Array = np.append(Original_Array,[40,50,60,70,80,90])
print(Appended_Array)

[10 20 30 40 50 60 70 80 90]


In [36]:
# 4) Create two numpy arrays and add the elements of both the arrays and store the result in sumArray.
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
sumArray = np.add(arr1,arr2) # or can also use - sumArray = arr1 + arr2  
print(sumArray)

[5 7 9]


In [ ]:
# 5) Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform the following tasks:
# a) Extract the 1st row from the array.
# b) Extract the last element from the array.

In [39]:
import numpy as np
array1 = np.arange(10,91,10).reshape(3,3)
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
print(array1[0])

[10 20 30]


In [42]:
print(array1[2:,2:])

[[90]]
